# Generated by Django 6.1.1 on 2026-09-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=50)),
                ('dish_name', models.CharField(max_length=255)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('item_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
