# Generated by Django 6.1.1 on 2026-10-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_dishsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_loyalty_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
